name: ðŸž Bug Report (compiler related)
description: If something does not work like expected, please report here!
labels: ["bug"]
title: "[ðŸž]"
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]  
        > TesserPack is currently in v0.
        > Which means it is not stable can cause unexpected results to the pack.
        >
        > Your bug reports will be helpful throughout development, so thank you!
  
  - type: input
    id: version
    attributes:
      label: "Version of TesserPack"
      placeholder: "v0.4.2"
      validations:
        required: true

  - type: textarea
    id: describe
    attributes:
      label: "Describe the bug"
      description: "It had to be clear description on what happend and what you expected to happend instead."
      placeholder: |
        I am doing this and that happend. I expect the compiler doing this and not doing that...
    validations:
      required: true

  - type: textarea
    id: reprod-url
    attributes:
      label: "Link to pack(s)"
      description: |
        Please provide a link to your pack(s) for better reproduction.
        It's fine if you have a snippet (such as affected assets) of your pack, if you want to keep a part of your pack as a secret.
      placeholder: |
        ex. https://github.com/USERNAME/REPO-NAME, https://drive.google.com/[...]
      validations:
        required: true

  - type: textarea
    id: reprod-steps
    attributes:
      label: "Steps to reproduce"
      placeholder: |
        1. Run tesserpack --compile "default" --in "./packs" --out "./pack.mcpack"
        2. [...]
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: "Configuration"
      description: |
        TesserPack has a configuration feature, which the compilation can vary.
        Leave blank if you don't use a config.
      placeholder: |
        ```
        {
          "compiler": {
            "json": {
              "strict": true
            },
            "png": {
              "compressLevel": 9,
              "quality": 100,
              "effort": 10
            },
            "jpg": {
              "quality": 100
            },
            "cache": true
          },
          "ignoreGlob": [
            "node_modules/*",
            "node_modules/**/*",
            ".git/*",
            ".git/**/*",
            ".vscode/*",
            ".vscode/**/*",
            ".github/*",
            ".github/**/*"
          ]
        }
        ```

  - type: textarea
    id: additional-info
    attributes:
      label: "Additional Information"
      description: "You could add an error message/stack or thoughts on fixing this issue or either willing to make a PR to fix this."
      placeholder: |
        Here is my error message

        ```
        SyntaxError: Expected property name or '}' in JSON at position 1 (line 1 column 2)
          at JSON.parse (<anonymous>)
          at ...
          at ...
        ```
        I think I can fix this bug...